---
# file: roles/zookeeper/tasks/main.yml

- name: Create user
  user:
    name: "{{ user.name }}"
    comment: "Deploy User - {{ user.name }}"
    shell: "{{ user.shell }}"
    createhome: no
    home: /opt/zookeeper
    system: yes
  sudo: yes

- name: Download
  get_url:
    url: "{{ zookeeper_url }}"
    dest: "/tmp/zookeeper.tar.gz"
    sha256sum: "{{ zookeeper_sha256 }}"

- name: Extract
  shell: "tar -xzf /tmp/zookeeper.tar.gz -C /opt/ && ln -sf /opt/zookeeper-{{ zookeeper_version }} /opt/zookeeper && chown -R {{ user.name }}:{{ user.name }} /opt/zookeeper* && rm -f /tmp/zookeeper.tar.gz chdir=/tmp"
  sudo: yes

- name: Remove src
  shell: "rm -rf {{ item }} chdir=/opt/zookeeper-{{ zookeeper_version }}"
  with_items:
  - "./bin/*.cmd"
  - "./conf/zoo*.cfg"
  - "./conf/log4j.properties"
  - "./contrib"
  - "./dist-maven"
  - "./docs"
  - "./recipes"
  - "./src"
  - "./*.xml"
  - "./*.txt"
  - "./zookeeper-*.jar.*"
  sudo: yes

- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  with_items:
  - "{{ zookeeper_dirs }}"
  - "{{ zookeeper_log }}"
  sudo: yes

- name: Copy zookeeper config
  template:
    src: zookeeper.properties.j2
    dest: /opt/zookeeper/conf/zookeeper.properties
    mode: 0644
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  sudo: yes

- name: Copy log4j config
  template:
    src: log4j.properties.j2
    dest: /opt/zookeeper/conf/log4j.properties
    mode: 0644
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  sudo: yes

- include: ../../../lib/run_app_with_runit.yml app_name=zookeeper zookeeper_log={{ zookeeper_log }}
