# file: roles/sudo_user/tasks/main.yml

- name: Create user
  user:
    name: "{{ ssh_user.name }}"
    comment: "Sudo User - {{ ssh_user.name }}"
    shell: /bin/bash

- name: Append user into groups (Ubuntu 14.04)
  user:
    name: "{{ ssh_user.name }}"
    groups: "adm,cdrom,sudo,dip,plugdev,lpadmin,sambashare"
    append: yes
  when: ansible_lsb.codename == 'trusty'

- name: Append user into groups (Ubuntu 16.04)
  user:
    name: "{{ ssh_user.name }}"
    groups: "adm,cdrom,sudo,dip,plugdev,lxd,lpadmin,sambashare"
    append: yes
  when: ansible_lsb.codename == 'xenial'

- name: Set password
  shell: "echo {{ ssh_user.name }}:{{ ssh_user.password }} | chpasswd"

- name: Sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ ssh_user.name }}"
    line: "{{ ssh_user.name }} ALL=(ALL) NOPASSWD: ALL"
