---
# file: roles/apt_update/tasks/main.yml

- name: Apt proxy setup
  template: src=apt.conf dest=/etc/apt/apt.conf mode=0644 owner=root group=root
  become: yes
  when: proxy_name is defined

- name: Update apt cache
  apt: update_cache=yes force=yes
  become: yes
  environment: "{{ proxy_env }}"

- name: Upgrade apt
  apt: upgrade=yes force=yes
  become: yes
  environment: "{{ proxy_env }}"
