---
# Deploy Html App

- name: "Deploy HTML App"
  hosts: all
  gather_facts: yes
  tasks:
    - include_tasks: lib/new_deploy_user.yml
      tags: install
    - include_tasks: lib/deploy_html_app.yml
      tags: [install,update]
