---

- name: "Deploy Java App"
  hosts: all
  gather_facts: yes
  tasks:
    - include: lib/new_deploy_user.yml user_name={{ app_name }}
      tags: install
    - include: lib/deploy_java_jar_app.yml user_name={{ app_name }}
      tags: [install,update]
    - include: lib/run_app_with_runit.yml user_name={{ app_name }}
      tags: install
    - include: lib/run_app_with_nginx.yml
      tags: nginx

    - name: "Restart App"
      tags: [update,restart]
      shell: "sv restart {{ app_name }}"
      become: yes
