---
# - name: "Deploy App"
#   hosts: app_nodes
#   gather_facts: yes
#   tasks:
#   - include: lib/new_deploy_user.yml user_name={{ app_name }}
#   - include: lib/deploy_ruby_app.yml user_name={{ app_name }}
#   - include: lib/run_app_with_runit.yml user_name={{ app_name }}
#   - include: lib/run_app_with_monit.yml
#   - include: lib/run_app_with_nginx.yml

- name: "Deploy Docker App"
  hosts: all
  gather_facts: yes
  tasks:
  - include: lib/deploy_docker_app.yml

- name: "Deploy App with Nginx"
  hosts: all
  gather_facts: yes
  tasks:
  - include: lib/run_app_with_nginx.yml app_name={{ app_name }}-in-docker
    when: nginx_and_ct is defined

- name: "Deploy App with Consul Template"
  hosts: all
  gather_facts: yes
  tasks:
  - include: lib/run_app_with_consul_template.yml
    when: nginx_and_ct is defined
