---
# - name: "Install zookeeper"
#   hosts: zookeeper_nodes
#   gather_facts: yes
#   roles:
#   - zookeeper

- name: "Install kafka"
  hosts: barcode_1s
  # hosts: kafka_nodes
  gather_facts: yes
  roles:
  - kafka
