- name: "Setup node"
  hosts: all
  gather_facts: yes

  roles:
  # - apt_update
  # - kernel_update
  # - common
  # - oh-my-zsh
  # - runit
  # - monit
  # - docker
  # - docker-compose
  # - docker-registry
