# Run site-node-initial with root user:
#   ansible-playbook site-node-initial.yml --ask-pass
# - include: site-node-initial.yml

- include: "site-node-common.yml"
# - include: "site-node-docker.yml"

# - include: "site-node-nginx.yml"
# - include: "site-node-java.yml"
# - include: "site-node-kafka.yml"
# - include: "site-node-app.yml"
# - include: "site-node-jetbrains.yml"


# - name: "Setup node"
#   hosts: barcode-1s
#   gather_facts: yes
#   roles:
  # - docker
  # - ruby
  # - confluent
  # - zookeeper
  # - kafka
  # - jruby
  # - nginx
  # - redis
  # - diamond
