#!/bin/sh

sv -w 20 start /etc/service/kafka || exit 1

export HOME=/opt/confluent
export PATH=/opt/confluent/bin:/usr/local/bin:/usr/bin:/bin
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export JAVA_HOME=/usr/lib/jvm/java-8-oracle

export KAFKA_HEAP_OPTS="-Xmx512M -Xms512M"
export LOG_DIR=/var/log/kafka
export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:/opt/confluent/etc/kafka/log4j.properties -Dkafka.logs.dir=$LOG_DIR"

cd $HOME
exec 2>&1
exec chpst -uconfluent $HOME/bin/schema-registry-start $HOME/etc/schema-registry/schema-registry.properties
