# file: roles/sudo_user/tasks/main.yml

- name: Create user
  user:
    name: "{{ ssh_user.name }}"
    comment: "Sudo User - {{ ssh_user.name }}"
    shell: /bin/bash
    groups: "adm,cdrom,sudo,dip,plugdev,libvirtd,lpadmin,sambashare"
    append: yes
  sudo: yes
  # remote_user: root

- name: Set password
  shell: "echo {{ ssh_user.name }}:{{ ssh_user.password }} | chpasswd"
  sudo: yes

- name: Sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ ssh_user.name }}"
    line: "{{ ssh_user.name }} ALL=(ALL) NOPASSWD: ALL"

- name: Fix hostname
  shell: "echo 127.0.0.1 localhost {{ ansible_hostname }} >> /etc/hosts"
  sudo: yes

