---
# file: roles/kafka/tasks/main.yml

- include: _install_bin.yml
- include: _configure.yml
- include: ../../../lib/run_app_with_runit.yml app_name=kafka app_home_dir={{ srv_home }} app_log_dir={{ srv_log_dir }}
