---
# file: roles/kafka/tasks/main.yml

- name: Create user
  user:
    name: "{{ user.name }}"
    comment: "Deploy User - {{ user.name }}"
    shell: "{{ user.shell }}"
    createhome: no
    home: /opt/kafka
    system: yes
  sudo: yes

- name: Download
  get_url:
    url: "{{ kafka_url }}"
    dest: "/tmp/kafka.tar.gz"
    sha256sum: "{{ kafka_sha256 }}"

- name: Extract
  shell: "tar -xzf /tmp/kafka.tar.gz -C /opt/ && ln -sf /opt/kafka_{{ scala_version }}-{{ kafka_version }} /opt/kafka && chown -R {{ user.name }}:{{ user.name }} /opt/kafka* && rm -f /tmp/kafka.tar.gz chdir=/tmp"
  sudo: yes

- name: Remove src
  shell: "rm -rf {{ item }} chdir=/opt/kafka_{{ scala_version }}-{{ kafka_version }}"
  with_items:
  - "./bin/windows"
  - "./config/zookeeper.properties"
  sudo: yes

- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  with_items:
  - "{{ kafka_log_dirs }}"
  - "{{ kafka_log }}"
  sudo: yes

- name: Copy kafka config
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/server.properties
    mode: 0644
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  sudo: yes

- name: Copy log4j config
  template:
    src: log4j.properties.j2
    dest: /opt/kafka/config/log4j.properties
    mode: 0644
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
  sudo: yes

- include: ../../../lib/run_app_with_runit.yml app_name=kafka kafka_log={{ kafka_log }}
