#!/bin/bash

export HOME={{ app_home_dir }}
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export PATH=$HOME/bin:$JAVA_HOME/bin:$JAVA_HOME/db/bin:$JAVA_HOME/jre/bin:/usr/local/bin:/usr/bin:/bin
export JVMFLAGS="-Xms1g -Xmx2g"

ZOOBINDIR="$HOME/bin"
ZOOCFGDIR="$HOME/conf"
ZOOCFG="$ZOOCFGDIR/zookeeper.properties"
ZOO_LOG_DIR={{ app_log_dir }}
ZOO_LOG4J_PROP="INFO,CONSOLE"

ZOOMAIN="org.apache.zookeeper.server.quorum.QuorumPeerMain"
CLASSPATH="$ZOOCFGDIR:$CLASSPATH"

LIBPATH=("${HOME}"/lib/*.jar)
for i in "${LIBPATH[@]}"
do
    CLASSPATH="$i:$CLASSPATH"
done

for i in "$HOME"/zookeeper-*.jar
do
  CLASSPATH="$i:$CLASSPATH"
done


if [ "x$SERVER_JVMFLAGS"  != "x" ]
then
    JVMFLAGS="$SERVER_JVMFLAGS $JVMFLAGS"
fi


cd $HOME
exec 2>&1
exec java "-Dzookeeper.log.dir=${ZOO_LOG_DIR}" "-Dzookeeper.root.logger=${ZOO_LOG4J_PROP}" \
    -cp "$CLASSPATH" $JVMFLAGS $ZOOMAIN "$ZOOCFG"
