---
# file: roles/jruby/tasks/main.yml

- name: Download jruby {{ jruby_version }}
  get_url: "url={{ jruby_url }} dest=/tmp/jruby-bin-{{ jruby_version }}.tar.gz sha256sum={{ jruby_sha256 }}"

- name: Extract ruby {{ jruby_version }}
  shell: "tar -xzf /tmp/jruby-bin-{{ jruby_version }}.tar.gz -C /opt/ && ln -sf /opt/jruby-{{ jruby_version }} /opt/jruby chdir=/tmp"
  sudo: yes

- name: Remove jruby from /tmp
  shell: "rm /tmp/jruby-bin-{{ jruby_version }}.tar.gz"
