---
# file: roles/ssh/tasks/main.yml

- name: Set up authorized_keys for the deploy user
  authorized_key:
    user: "{{ ssh_user.name }}"
    key: "{{ item }}"
  with_file:
    - "group_files/keys/ssh/{{ ssh_key }}.pub"

- name: configures SSH daemon
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^Port", line: "Port {{ ssh_port }}" }
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "PasswordAuthentication (yes|no)", line: "PasswordAuthentication no" }
  notify:
    - restart ssh
