---
# file: roles/docker-compose/tasks/main.yml

- name: pip
  apt:
    name: python-pip
    state: latest
    install_recommends: yes
  become: yes

- name: Docker Compose
  shell: "pip install --upgrade --proxy={{ proxy_env.http_proxy }} docker-compose"
  become: yes
  when: proxy_env.http_proxy is defined

- name: Docker Compose
  shell: "pip install --upgrade docker-compose"
  become: yes
  when: proxy_env.http_proxy is undefined
