---
# file: roles/oh-my-zsh/tasks/main.yml

- name: Install some packages
  apt: package={{ item }} state=latest install_recommends=yes
  sudo: yes
  with_items:
    - zsh
    - git

- name: Load from /etc/profile.d/* env
  copy:
    src: zshenv
    dest: /etc/zsh/zshenv
    mode: 0644
    owner: root
    group: root
  sudo: yes

- name: Install oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    accept_hostkey: yes
    dest: "~/.oh-my-zsh"
    version: master
    depth: 1
  environment: "{{ proxy_env }}"
  become: yes
  become_user: "{{ ssh_user.name }}"

- name: Copy zshrc file
  copy:
    src: zshrc
    dest: ~/.zshrc
    mode: 0644
  become: yes
  become_user: "{{ ssh_user.name }}"

- name: Change bash to zsh for current user
  user: name={{ ssh_user.name }} shell=/bin/zsh
  sudo: yes

- name: Remove bash files
  shell: "rm -f ~/.bash* ~/.profile"
