#!/bin/bash

export HOME=/opt/youtrack
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export PATH=$HOME/bin:$JAVA_HOME/bin:$JAVA_HOME/db/bin:$JAVA_HOME/jre/bin:/usr/local/bin:/usr/bin:/bin

export http_proxy="http://proxy.picompany.ru:8080"
export https_proxy="http://proxy.picompany.ru:8080"
export ftp_proxy="http://proxy.picompany.ru:8080"
export no_proxy="localhost,127.0.0.1,.dsk2.picompany.ru"

cd $HOME
exec 2>&1
exec chpst -uyoutrack $HOME/bin/youtrack.sh run
