---
# file: roles/java/tasks/main.yml

# - name: Deinstall OpenJDK
#   tags: java
#   apt: package=openjdk-* state=absent purge=yes
#   become: yes

# - name: Deinstall Java
#   tags: java
#   apt: package=oracle-java{{ java_version }}-installer* state=absent purge=yes
#   become: yes

- name: Install add-apt-repostory
  tags: java
  apt: name=software-properties-common state=latest
  become: yes

- name: Add Webupd8Team Repo
  apt_repository:
    repo=ppa:webupd8team/java
    state=present
    update_cache=yes
  become: yes

- name: Accept Java 8 License
  debconf: name='oracle-java{{ java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes

# # - name: Automatically select the Oracle License
# #   tags: java
# #   shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
# #   become: yes

- name: Install Oracle Java 8
  apt: name={{item}} state=latest install_recommends=yes
  with_items:
    - oracle-java{{ java_version }}-installer
    - ca-certificates
    - oracle-java{{ java_version }}-set-default
  become: yes

# - name: Install Java
#   tags: java
#   action: apt pkg=oracle-java{{ java_version }}-installer state=latest install_recommends=yes
#   become: yes
#   # environment: "{{ proxy_env }}"

- name: Add JAVA_HOME env
  tags: java
  action: lineinfile dest=/etc/environment regexp=^JAVA_HOME= line=JAVA_HOME="/usr/lib/jvm/java-{{ java_version }}-oracle"
  become: yes
