---
# file: roles/common/tasks/main.yml

- import_tasks: _locale.yml
- import_tasks: _time.yml
- import_tasks: _ppa_repos.yml
- import_tasks: _sysctl.yml
- import_tasks: _soft.yml
# - include: _proxy.yml
