---
# file: roles/docker/tasks/install.yml

- name: Add Key for Docker Repo
  tags: docker
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  become: yes
  environment: "{{ proxy_env }}"

- name: Update apt cache
  apt: update_cache=yes force=yes
  become: yes
  environment: "{{ proxy_env }}"

- name: Add Docker Repo
  tags: docker
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    state: present
    update_cache: yes
  become: yes
  environment: "{{ proxy_env }}"

- name: Install Prerequisites
  tags: docker
  shell: "apt-get install {{ item }}"
  with_items:
  - "apt-transport-https"
  - "ca-certificates"
  - "linux-image-extra-$(uname -r)"
  become: yes
  environment: "{{ proxy_env }}"

- name: Install Docker Engine
  tags: docker
  apt:
    name: docker-engine
    state: latest
    install_recommends: yes
  become: yes

- name: Add Docker to start on boot
  service:
    name: docker
    enabled: yes
  become: yes

- name: Copy conf file
  template:
    src: docker.j2
    dest: /etc/default/docker
    mode: 0644
    owner: root
    group: root
  when: proxy_env.http_proxy is defined
  notify: restart docker
  become: yes

- name: Enable IP Forwarding for Containers
  copy:
    src: 70-docker-ip-forwarding.conf
    dest: /etc/sysctl.d/70-docker-ip-forwarding.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Reload sysctl settings
  service: name=procps state=started enabled=yes
  become: yes
