---
# file: roles/docker/tasks/docker-py.yml

- name: Install pip
  apt:
    name: python-pip
    state: latest
    install_recommends: yes
  become: yes

- name: Install Docker-Py
  shell: "pip install docker-py"
  become: yes
  environment: "{{ proxy_env }}"
